### ISSUE TITLE
How to correctly change skin_url?

### ISSUE THREAD

**Issue by leeloo23** [teamOnHQ/tinymce#5]
What would be the best way to include new skin (generated with TinyMCE Skin Creator)?. Could you provide an example how to do it? 

I tried to put another folder (with my skin) next to yours in ~/.meteor/packages/teamon_tinymce/skins and then change the skin_url on tinymce.init but I got an error:
`Did not parse stylesheet at 'http://localhost:3000/packages/tinymce/skins/custom/skin.min.css' because non CSS MIME types are not allowed in strict mode.`

Meteor version 1.3.2.4

Thanks!

**Comment by boldkhuu** [comment]
@leeloo23 You can put your skin folder to the `/public` directory of your meteor project. (e.g: /public/tinymce_custom_skin). Then your init function must be like below:
```
tinymce.init({
  selector: 'textarea',
  skin_url: '/tinymce_custom_skin',
});
```

**Comment by leeloo23** [comment]
@boldkhuu Thank for your reply. I tried that before as well and got the same thing.
Never the less I tried it one more time and this is the exact thing I got from Chrome Dev Tools:
![screen shot 2016-06-21 at 07 30 10](https://cloud.githubusercontent.com/assets/6362351/16218904/392cbce6-3782-11e6-99f0-35a99bf19d78.png)

**Comment by boldkhuu** [comment]
@leeloo23 It looks like you include `/public` in your path. Your path must be `/tinymce/custom`.

**Comment by leeloo23** [comment]
@boldkhuu works like a charm! Thanks so much! Easy oversight from my side. 👍

**Comment by boldkhuu** [comment]
@leeloo23 You are welcome.
